# Site
repository: https://github.com/alvaro-roldan-capponi/cv
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Alvaro Roldan Capponi
title: DevOps Engineer | Tech Lead
email: varo.roldan@gmail.com
# phone: '+5491154731120'
# website: Your website (eg. https://google.com)(optional)

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
# github_username:  alvaro-roldan-capponi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: alvaro-roldan-capponi-24b19314
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: mypicture/Alvaro_Roldan_Capponi.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a Tech Lead DevOps Engineer with over 15 years experience on IT, managing multicultural global teams.
  My main bussiness expertise are retail and banking, where I've helped integrate different groups by creating pipelines to make Development, Operations and Security areas work together.
  My goal is to help companies, from all backgrounds and sizes, to move to DevOps culture, integrating agile methodologies, to achieve a fast and secure development and production deployments.


# DevOps Engineer with experience in national and international projects leadership and in cross-functional and cross-cultural teams integrated by
# developers, architects, Product Owners, system operators (SysOps) and other IT professionals to develop, test and implement in production applications with
# dedicated infrastructure. I have a background of over 15 years in the IT field workingn different positions such as DevOps, now as a Tech Lead, Developer, Functional
# Analyst and Project Manager.
# Throughout my professional career, I have coordinated teams directly and indirectly, always with a focus on organizing tasks, meeting security objectives and metrics. I
# consider that I have a great capacity to adapt to different work teams and environments, to plan and coordinate projects at a regional and international level and to establish
# interpersonal relationships based on trust and collaboration.



# Qué sos?
# Qué hice?
# Qué principios defiendo en lo profesional?


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **PERSONAL SKILLS**
    - 
      Analytical thinking | Conceptual reasoning | Critical thinking | Time management | Organizational awareness | Vision focused on the business |
      Decision making | Customer orientation Flexibility | Ability to work under pressure | Tolerance to stress and/or frustration | Innovation and creativity |
      Leadership | Active listening | Conflict resolution | Strategic orientation | Assertiveness | Self-control | Motivation to achievement |
      Learning attitude and continuous improvement.

  *Skills*
    - AWS Services
    - Docker: Dockerfiles / docker-compose / multistage
    - Kubernetes: EKS
    - CI/CD: Gitlab-ci / Jenkins
    - Python
    - NodeJS
    - Bash
    - Linux
    - Terraform
    - Jenkins
    - Git
    - Agile Methodologies

  *Languages*
    - English: Advanced
    - Spanish: Native

  *TRAININGS*
    - AWS Certified Developer (2020)
    - AWS CloudFormation Master Class
    - Docker Mastery: with Kubernetes + Swarm from a Docker Captain
    - Complete Python Bootcamp: From Zero to Hero in Python (2019)

  *PROFESSIONAL SKILLS*
    - Culture and methodology of Devops
    - Support to productive infrastructure
    - Pipelines for application implementation
    - Platform development in Kubernetes
    - Generation of infrastructure, orchestration and security services.
    - Cloud Engineering (AWS Services)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
